- name: Instalar Docker
  include_tasks: ../common/install_docker.yml

- name: Copiar configuração do PostgreSQL
  copy:
    src: "../../../docker/banco/"
    dest: "/home/vagrant/banco"

- name: Iniciar container do banco
  become: yes
  community.docker.docker_compose_v2:
    project_src: "/home/vagrant/banco"
    build: true
    remove_orphans: true
    recreate: always
