- name: Instalar Docker
  include_tasks: ../common/install_docker.yml

- name: Criar diretório de dados
  file:
    path: "/home/vagrant/dataset/dados"
    state: directory

- name: Copiar scripts e dados
  copy:
    src: "../../../docker/dataset/"
    dest: "/home/vagrant/dataset"

- name: Construir container do dataset
  community.docker.docker_image:
    name: "dataset-img"
    build:
      path: "/home/vagrant/dataset"
    source: build

- name: Executar container
  community.docker.docker_container:
    name: "dataset-container"
    image: "dataset-img"
    ports: "80:80"
    restart_policy: always
    state: started